elasticsearch-data:
  image: busybox
  container_name: elasticsearch-data
  volumes:
      - /usr/share/elasticsearch/data

elasticsearch:
  image: elasticsearch
  container_name: elasticsearch
  volumes_from:
      - elasticsearch-data
  restart: always
  net: host
  ports:
      - "9200:9200"
      - "9300:9300"
  command: elasticsearch -Des.node.name="logstash"
